#!/usr/bin/env python3
"""
Compute full-24h HRV metrics for Nagoya subjects.
==================================================

Reads the raw Nagoya RRi files, applies physiological filtering, and computes
NeuroKit2 time-domain/frequency HRV metrics plus DFA alpha1 over the complete
recording. This reproduces japan_recalc_metrics.csv with a fully documented,
reproducible pipeline.

Why this exists
---------------
The original japan_recalc_metrics.csv was generated by an undocumented script
that is no longer available. Its exact subject-exclusion criterion is unknown.
This script makes the process explicit: all 50 subjects are attempted; those
for which computation fails (e.g. recording too short for ULF/VLF bands, or
NeuroKit2 internal errors) are logged and excluded rather than dropped silently.

Output columns match the original file exactly:
    Subject, Group, HRV_MeanNN, HRV_SDNN, ..., DFA_alpha1

Output
------
    data/japan_recalc_metrics.csv

Requires
--------
    Nagoya raw RRi files (not in public_release — available on request):
    processed_rri/*_RRi.txt   format: rel_time_s  rri_s  (space-separated)
"""

import os
import warnings
import numpy as np
import pandas as pd
import neurokit2 as nk

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE           = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Resolved relative to the repo root so the script is portable; override with
# the NAGOYA_ROOT environment variable if the tree is laid out differently.
_NAGOYA_ROOT   = os.environ.get(
    "NAGOYA_ROOT",
    os.path.abspath(os.path.join(BASE, "..", "..", "Nagoya", "public_release")))
NAGOYA_RRI_DIR = os.path.join(_NAGOYA_ROOT, "data", "processed_rri")
NAGOYA_META    = os.path.join(_NAGOYA_ROOT, "data", "metadata", "metadata.csv")
OUT_CSV        = os.path.join(BASE, "data", "japan_recalc_metrics.csv")

# ── Suzuki et al. (2022) vagal-metric convention ──────────────────────────────
# The source publication for this dataset (J Neural Transm 129:1299-1306, p.1301)
# excludes RR intervals whose adjacent difference is >= 100 ms before computing
# RMSSD and pNN50, "to avoid the effects of extrasystoles and artifacts".
#
# Without it, 24 h of free-living recording gives RMSSD ~3.7x and pNN50 ~2x the
# published values (ours 81.9/55.1 ms vs their 22.2/15.0 ms). Those inflated
# values fed Figures 5 and 7. Applying the rule restores agreement with the
# published cohort and makes Nagoya comparable to the short resting recordings.
# See Multicenter/SUZUKI_CONSISTENCY_CHECK.md sec. 1.
SUZUKI_DIFF_EXCL_MS = 100.0

# ── Quality thresholds ─────────────────────────────────────────────────────────
RRI_MIN_S    = 0.300   # physiological lower bound (s) — 200 bpm max
RRI_MAX_S    = 2.000   # physiological upper bound (s) — 30 bpm min
MIN_BEATS    = 5_000   # minimum clean beats to attempt HRV calculation

# Sampling rate used to convert RRi to peak indices for nk.hrv()
FS = 1000

# Columns to retain from nk.hrv() output (subset matching the original file)
KEEP_COLS = [
    "HRV_MeanNN", "HRV_SDNN", "HRV_SDANN1", "HRV_SDNNI1",
    "HRV_SDANN2", "HRV_SDNNI2", "HRV_SDANN5", "HRV_SDNNI5",
    "HRV_RMSSD", "HRV_SDSD", "HRV_CVNN", "HRV_CVSD",
    "HRV_MedianNN", "HRV_MadNN", "HRV_MCVNN", "HRV_IQRNN",
    "HRV_SDRMSSD", "HRV_Prc20NN", "HRV_Prc80NN",
    "HRV_pNN50", "HRV_pNN20",
    "HRV_MinNN", "HRV_MaxNN", "HRV_HTI", "HRV_TINN",
    "HRV_ULF", "HRV_VLF", "HRV_LF", "HRV_HF", "HRV_VHF", "HRV_TP",
    "HRV_LFHF", "HRV_LFn", "HRV_HFn", "HRV_LnHF",
    "HRV_SD1", "HRV_SD2",
]


# ── DFA alpha1 (short-range, 4–16 beats) ──────────────────────────────────────

def _dfa_fluctuation(y, n):
    n_segs = len(y) // n
    if n_segs < 2:
        return np.nan
    y_trim = y[:n_segs * n].reshape(n_segs, n)
    t = np.arange(n)
    A = np.column_stack([t, np.ones(n)])
    coefs, _, _, _ = np.linalg.lstsq(A, y_trim.T, rcond=None)
    residuals = y_trim - (A @ coefs).T
    return np.sqrt(np.mean(residuals ** 2))


def dfa_alpha1(rri_ms, scale_min=4, scale_max=16, n_scales=10):
    """Short-range DFA scaling exponent."""
    y = np.cumsum(rri_ms - np.mean(rri_ms))
    scales = np.unique(
        np.round(np.logspace(np.log10(scale_min), np.log10(scale_max), n_scales)).astype(int)
    )
    scales = scales[(scales >= 4) & (scales <= len(rri_ms) // 4)]
    log_n, log_F = [], []
    for n in scales:
        F = _dfa_fluctuation(y, n)
        if np.isfinite(F) and F > 0:
            log_n.append(np.log10(n))
            log_F.append(np.log10(F))
    if len(log_n) < 3:
        return np.nan
    alpha, _ = np.polyfit(log_n, log_F, 1)
    return alpha


# ── RRi loader ─────────────────────────────────────────────────────────────────

def load_rri_full(filepath):
    """
    Load all RRi values from a Nagoya *_RRi.txt file.
    Format: two space-separated columns — cumulative_time_s  rri_s
    Returns: (rri_s array, filtered to physiological bounds)
    """
    df = pd.read_csv(filepath, header=None, sep=r"\s+", names=["t", "rri"])
    rri = df["rri"].astype(float).values
    return rri[(rri >= RRI_MIN_S) & (rri <= RRI_MAX_S)]


# ── Per-subject processing ─────────────────────────────────────────────────────

def process_subject(sid, group, rri_dir):
    """
    Returns a dict of HRV metrics, or None if computation fails.
    All failure reasons are returned as the second element.
    """
    rri_path = os.path.join(rri_dir, f"{sid}_RRi.txt")
    if not os.path.exists(rri_path):
        return None, "RRi file not found"

    try:
        rri_s = load_rri_full(rri_path)
    except Exception as e:
        return None, f"load error: {e}"

    if len(rri_s) < MIN_BEATS:
        return None, f"too few clean beats ({len(rri_s)} < {MIN_BEATS})"

    rri_ms = rri_s * 1000.0
    peaks  = np.concatenate([[0], np.cumsum(rri_ms)]).astype(int)

    try:
        hrv = nk.hrv(peaks, sampling_rate=FS, show=False)
    except Exception as e:
        return None, f"nk.hrv() failed: {e}"

    row = {"Subject": sid, "Group": group}
    for col in KEEP_COLS:
        row[col] = hrv[col].values[0] if col in hrv.columns else np.nan
    row["DFA_alpha1"] = dfa_alpha1(rri_ms)

    # Keep the unfiltered values for transparency, then override RMSSD / pNN50
    # with the Suzuki convention (see SUZUKI_DIFF_EXCL_MS above).
    row["HRV_RMSSD_unfiltered"] = row.get("HRV_RMSSD", np.nan)
    row["HRV_pNN50_unfiltered"] = row.get("HRV_pNN50", np.nan)
    d = np.diff(rri_ms)
    d = d[np.abs(d) < SUZUKI_DIFF_EXCL_MS]
    if d.size > 1:
        row["HRV_RMSSD"] = float(np.sqrt(np.mean(d ** 2)))
        row["HRV_pNN50"] = float(100.0 * np.mean(np.abs(d) > 50.0))
    row["vagal_metric_convention"] = f"Suzuki2022_adjdiff_lt_{int(SUZUKI_DIFF_EXCL_MS)}ms"
    return row, None


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("\n" + "=" * 68)
    print("  Nagoya — Full-24h HRV Metrics (japan_recalc_metrics.csv)")
    print("=" * 68)
    print(f"  RRi source : {NAGOYA_RRI_DIR}")
    print(f"  Min beats  : {MIN_BEATS:,}")
    print(f"  RRi bounds : {RRI_MIN_S:.2f} – {RRI_MAX_S:.2f} s")
    print("=" * 68)

    if not os.path.exists(NAGOYA_RRI_DIR):
        print(f"\n  ERROR: RRi directory not found: {NAGOYA_RRI_DIR}")
        print("  japan_recalc_metrics.csv cannot be regenerated without raw data.")
        return

    meta = pd.read_csv(NAGOYA_META)
    results, failed = [], []

    for _, row in meta.sort_values("Subject_ID").iterrows():
        sid   = row["Subject_ID"]
        # Canonical group labels: Nagoya metadata writes 'PD' / 'control',
        # every other cohort uses 'PD' / 'Control'.
        group = {"pd": "PD", "control": "Control"}.get(
            str(row["Group"]).strip().lower(), str(row["Group"]).strip())
        print(f"  {sid}  ({group:<8}) ... ", end="", flush=True)
        metrics, reason = process_subject(sid, group, NAGOYA_RRI_DIR)
        if metrics:
            results.append(metrics)
            print(f"OK  (n={len(results)})")
        else:
            failed.append((sid, reason))
            print(f"SKIP — {reason}")

    if not results:
        print("\n  No subjects processed successfully.")
        return

    # Build output with columns in original order
    col_order = (["Subject", "Group"] + KEEP_COLS + ["DFA_alpha1"])
    df = pd.DataFrame(results)[col_order]
    df.to_csv(OUT_CSV, index=False)

    print(f"\n{'=' * 68}")
    print(f"  Processed : {len(results)} subjects")
    print(f"  Skipped   : {len(failed)} subjects")
    if failed:
        for sid, reason in failed:
            print(f"    {sid}: {reason}")
    print(f"  Saved → {OUT_CSV}")
    print("=" * 68 + "\n")


if __name__ == "__main__":
    main()
